### ISSUE TITLE
Bond mode and xmit_hash_policy should be set before another bond properties

### ISSUE THREAD

**Issue by stamak** [xenolog/l23network#138]
lacp_rate and bond mode are not set correctly 

root@node-20:~# grep 'Bonding Mode' /proc/net/bonding/bond*
/proc/net/bonding/bond0:Bonding Mode: IEEE 802.3ad Dynamic link aggregation
/proc/net/bonding/bond1:Bonding Mode: load balancing (round-robin)
Even if a bond is configured in 802.3ad mode it always have lacp_rate=slow.

**Comment by xenolog** [comment]
FUEL-Change-Id: Ib76b88a8ed272d3465b1871db9f4b7b267888d64
